package toyproject.genshin.teybatguide.base.value;

public enum Domain {
    CHARACTER, RESOURCES, CHARACTER_TALENTS, CHARACTER_SPECIFICATIONS, CHARACTER_ASCEND, CHARACTER_BANNER,
    ARTIFACT, CHARACTER_ARTIFACT,
    WEAPON, CHARACTER_WEAPON, WEAPON_ASCEND, WEAPON_BANNER,
    USER,
    DOMAIN, EVENT;
}
