package toyproject.genshin.teybatguide.domain.value;

public enum Domain {
    CHARACTER, RESOURCES, CHARACTER_TALENTS, CHARACTER_SPECIFICATIONS, CHARACTER_ASCEND, CHARACTER_BANNER,
    ARTIFACT, CHARACTER_ARTIFACT,
    WEAPON, CHARACTER_WEAPON, WEAPON_ASCEND;
}
